# Generated by Django 5.1 on 2026-09-06 14:28

import api.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StorageShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('occupied', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('GUARD', 'Guard'), ('RESIDENT', 'Resident')], default='RESIDENT', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GuardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active_guard', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(default=api.models.generate_parcel_id, max_length=20, unique=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('AWAITING_PICKUP', 'Awaiting Pickup'), ('OVERDUE', 'Overdue'), ('HANDED_OVER', 'Handed Over'), ('CANCELLED', 'Cancelled')], default='AWAITING_PICKUP', max_length=20)),
                ('pickup_pin', models.CharField(default=api.models.generate_pickup_pin, max_length=4)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='api.carrier')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='api.flat')),
                ('handed_over_by', models.ForeignKey(help_text='Guard who handed over the parcel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_over_parcels', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(help_text='Guard who registered the parcel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_parcels', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(help_text='The resident receiving the parcel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_parcels', to=settings.AUTH_USER_MODEL)),
                ('shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='api.storageshelf')),
            ],
        ),
        migrations.CreateModel(
            name='PickupVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='api.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='api.flat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='api.tower'),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('tower', 'number')},
        ),
    ]
