# Generated by Django 5.1 on 2026-09-07 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageshelf',
            name='occupied',
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivery_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('FOOD', 'Food Delivery')], default='NORMAL', max_length=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('NEW_PARCEL', 'New Parcel'), ('FOOD_DELIVERY', 'Food Delivery'), ('OVERDUE', 'Overdue Parcel'), ('HANDOVER', 'Handover Completed')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.parcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
