# Generated by Django 5.1 on 2026-09-08 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_storageshelf_occupied_parcel_delivery_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, max_length=100)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_name', models.CharField(max_length=100)),
                ('delivery_type', models.CharField(choices=[('PARCEL', 'Parcel'), ('FOOD', 'Food Delivery')], max_length=10)),
                ('payment_type', models.CharField(choices=[('PREPAID', 'Prepaid'), ('COD', 'Cash on Delivery (COD)')], max_length=10)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_delivery_date', models.DateField()),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='expected_deliveries/')),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('CANCELLED', 'Cancelled')], default='EXPECTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(help_text='Resident who expects the delivery', on_delete=django.db.models.deletion.CASCADE, related_name='expected_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
