# Generated by Django 5.1 on 2026-09-08 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expecteddelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='expected_delivery',
            field=models.OneToOneField(blank=True, help_text='The pre-registered expected delivery this parcel fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_parcel', to='api.expecteddelivery'),
        ),
    ]
