# Generated by Django 5.1 on 2026-09-08 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parcel_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='cod_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='cod_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_VERIFIED', 'Payment Verified')], default='NOT_APPLICABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='parcel',
            name='cod_verified_by',
            field=models.ForeignKey(blank=True, help_text='Guard who verified COD payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cod_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_type',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('COD', 'Cash on Delivery (COD)')], default='PREPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('AWAITING_PICKUP', 'Awaiting Pickup'), ('OVERDUE', 'Overdue'), ('HANDED_OVER', 'Handed Over'), ('CANCELLED', 'Cancelled'), ('DELIVERY_ATTEMPTED', 'Delivery Attempted')], default='AWAITING_PICKUP', max_length=20),
        ),
    ]
