# Generated by Django 5.1 on 2026-09-08 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_parcel_cod_amount_parcel_cod_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='cod_status',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='cod_verified_by',
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_cod_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash (Direct to Courier)'), ('UPI', 'UPI / Remote Digital Link'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Payment Verified to Courier'), ('FAILED', 'Unpaid / Delivery Attempted'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20),
        ),
    ]
