# Generated by Django 5.1 on 2026-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_parcel_cod_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expecteddelivery',
            name='is_open_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expecteddelivery',
            name='open_box_resolution',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('DIRECT_RESIDENT_HANDOVER', 'Direct Handover at Gate'), ('RESCHEDULED', 'Rescheduled - Returned with Courier')], default='NOT_APPLICABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='parcel',
            name='is_open_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcel',
            name='open_box_resolution',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('DIRECT_RESIDENT_HANDOVER', 'Direct Handover at Gate'), ('RESCHEDULED', 'Rescheduled - Returned with Courier')], default='NOT_APPLICABLE', max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('AWAITING_PICKUP', 'Awaiting Pickup'), ('OVERDUE', 'Overdue'), ('HANDED_OVER', 'Handed Over'), ('CANCELLED', 'Cancelled'), ('DELIVERY_ATTEMPTED', 'Delivery Attempted'), ('RESCHEDULED', 'Rescheduled')], default='AWAITING_PICKUP', max_length=20),
        ),
    ]
