# Generated by Django 5.1 on 2026-09-09 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_expecteddelivery_is_open_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='collected_by_role_type',
            field=models.CharField(choices=[('PRIMARY_RESIDENT', 'Primary Resident'), ('DELEGATED_FLATMATE', 'Delegated Flatmate')], default='PRIMARY_RESIDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='parcel',
            name='delegated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='is_delegated',
            field=models.BooleanField(default=False),
        ),
    ]
